name: Update README with JSON Table
on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16.2
      uses: actions/setup-node@v2
      with:
        node-version: 16.2

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README
      run: |
        python new.py  # Execute the Python script to update the README
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
