name: Update README with Python Output

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Python Script
        id: run_python
        run: |
          python3 update-readme.py
        

      - name: Update README
        run: |
          MARKDOWN_CONTENT="${{ steps.run_python.outputs.stdout }}"
          sed -i '/<!--START_SECTION:python-output-->/,/<!--END_SECTION:python-output-->/d' README.md
          echo "<!--START_SECTION:python-output-->" >> README.md
          echo "$MARKDOWN_CONTENT" >> README.md
          echo "<!--END_SECTION:python-output-->" >> README.md
          git config --local user.email "swathipriyarv23@gmail.com"
          git config --local user.name "Swathi23345"
          git commit -am "Update README with Python output" || true
          git push
