name: Update README with Python Output

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Specify the desired Python version

    - name: Generate Output
      run: python new.py > output.md

    - name: Update README
      run: |
        OUTPUT_CONTENT=$(cat output.md)
        sed -i 's|<!-- OUTPUT START -->.*<!-- OUTPUT END -->|<!-- OUTPUT START -->\n'"$OUTPUT_CONTENT"'\n<!-- OUTPUT END -->|' README.md
      env:
        OUTPUT_CONTENT: ${{ steps.generate_output.outputs.output_content }}
